# Generated by Django 4.0.1 on 2022-01-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmovidu_app', '0002_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='cname',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
