# Generated by Django 4.0.1 on 2022-01-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmovidu_app', '0003_job_cname'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=300)),
            ],
        ),
    ]
